docs update
architect-templates/flask pull request #11
Opened 2022-09-16 01:38 UTC by ryan-cahill

## Overview
Updated docs to deploy the component config file rather than the component by name

## Changes
* Doc updates related to deployments

## Pictures

### Local

![image](https://user-images.githubusercontent.com/8558567/190536916-4d3bb426-6f7e-4b36-b730-3f1c5ff97c4e.png)

### Remote

![image](https://user-images.githubusercontent.com/8558567/190537834-018e352a-b0a3-4e48-964f-bc6bcead53d3.png)

![image](https://user-images.githubusercontent.com/8558567/190537810-2356d18d-42e3-4365-8665-d8abe0327080.png)

## TODO List
Before merging, a PR will need
- [ ] Signoff from @Zach-at-Arch for UX
- [ ] Signoff from one other engineer at Architect.io

2022-09-16 14:38 UTC, Zach-at-Arch commented on README.md
> +You can then [deploy the application](https://docs.architect.io/getting-started/introduction/#deploy-to-the-cloud). To do this, run the following command. "example-environment" is the name of the fre
Change to (keep the hyper link) -
You can then deploy the application by running the command below. Note that “example-environment” is the free environment that is created with your Architect account.

2022-09-16 14:39 UTC, Zach-at-Arch requested changes
Small wording change for better clarity.

2022-09-19 17:17 UTC, Zach-at-Arch approved these changes

2022-09-20 21:42 UTC, mtgoncalves1 approved these changes
It looks good. Both local and remote deployments worked.

2022-10-04 17:36 UTC, merged